::DECLARE FUNCTION AS FN
:FN
::HIDE ALL INRELEVANT TEXT
@ECHO off

::ASK FOR USER INPUT AS PROJECT VARIABLE
ECHO Please Enter Your Project Folder Name,
ECHO !Important: This Will Also Be Your Key Name And Alias.
SET /P PROJECT=Enter:
::IF INPUT RERUN FUNCTION IF USER INPUT IS EMPTY
IF NOT DEFINED PROJECT GOTO FN

:CONFIRMKEY
::ASK IF USER ALREADY HAVE KEY
ECHO Do You Have Key Already?
SET /P KEYTOOL=(Y/N):
::IF STATEMENT YOU KNOW
IF "%KEYTOOL%"=="Y" (
    GOTO HAVEKEY
) ELSE IF "%KEYTOOL%"=="y" (
    GOTO HAVEKEY
) ELSE IF "%KEYTOOL%"=="N" (
    GOTO BUILFROMSTART
) ELSE IF "%KEYTOOL%"=="n" (
    GOTO BUILFROMSTART
) ELSE (
    GOTO CONFIRMKEY
)

:HAVEKEY
::ASK IF USER ALREADY HAVE KEY
ECHO Did You Configure Your Gradle Build Already?
SET /P KEYTOOL=(Y/N):
::IF STATEMENT YOU KNOW
IF "%KEYTOOL%"=="Y" (
    GOTO BUILDAPK
) ELSE IF "%KEYTOOL%"=="y" (
    GOTO BUILDAPK
) ELSE IF "%KEYTOOL%"=="N" (
    GOTO BUILDGRADLE
) ELSE IF "%KEYTOOL%"=="n" (
    GOTO BUILDGRADLE
) ELSE (
    GOTO HAVEKEY
)

:BUILFROMSTART
::CHANGE DIRECTORY TO JAVA FOLDER
CD C:/Program Files/Java/
::FIND THE LATEST JAVA VERSION BY THE CREATE DATE OF FOLDER
FOR /F "delims=" %%i IN ('dir /b /ad-h /t:c /od') DO SET JAVA=%%i
::CHANGE DIRECTORY TO BIN FOLDER
CD ./%JAVA%/BIN
::RUN JAVA KEYTOOL TO GENERATE SINGNATURE KEY
START keytool -genkey -v -keystore %PROJECT%.keystore -alias %PROJECT% -keyalg RSA -keysize 2048 -validity 10000

::PRINT THE BASIC KEY INFO
ECHO Your Keystore Will Be %PROJECT%
ECHO And The Alias is %PROJECT%
PAUSE
::COPY KEYSTORE TO PROJECT DIRECTORY
XCOPY %PROJECT%.keystore E:\Leo\%PROJECT%\android\app
::CHANGE DIRECTORY TO .GRADLE AND OPEN GRADLE.PROPERTY FILE
CD C:/USERS/Leo/.gradle/
::MAKE A TIMESTAMP
SET YEAR=%date:~0,4%
SET MONTH=%date:~5,2%
SET DAY=%date:~8,2%
FOR /F "tokens=1-2 delims=/:" %%a in ("%TIME%") DO (SET TIMES=%%a%%b)

::RENAME OLD FILE WITH TIMESTAMP AS BACKUP
REN gradle.properties old_%YEAR%%MONTH%%DAY%%TIMES%.properties
::WE NEED PASSWORDS!
:FIRSTPASS
SET /P PASSWORD1=Enter Your Store Password:
IF NOT DEFINED PASSWORD1 GOTO FIRSTPASS
:SECONDPASS
SET /P PASSWORD2=Enter Your Key Password:
IF NOT DEFINED PASSWORD2 GOTO SECONDPASS

SET /P CONFIRMPASS=Proceed?(Y/N)

:CONFIRMPASS2
::IF STATEMENT YOU KNOW
IF "%CONFIRMPASS%"=="Y" (
    GOTO MAKEGRADLEPROPERTIES
) ELSE IF "%CONFIRMPASS%"=="y" (
    GOTO MAKEGRADLEPROPERTIES
) ELSE IF "%CONFIRMPASS%"=="N" (
    GOTO FIRSTPASS
) ELSE IF "%CONFIRMPASS%"=="n" (
    GOTO FIRSTPASS
) ELSE (
    GOTO CONFIRMPASS2
)

:MAKEGRADLEPROPERTIES
::MAKE A GRADLE.PROPERTIES FILE WITH BEAUTIFUL(!?) FORMAT
@(
    ECHO MYAPP_RELEASE_STORE_FILE=%PROJECT%.keystore 
    ECHO MYAPP_RELEASE_KEY_ALIAS=%PROJECT%
    ECHO MYAPP_RELEASE_STORE_PASSWORD=%PASSWORD1%
    ECHO MYAPP_RELEASE_KEY_PASSWORD=%PASSWORD2%
) >> gradle.properties

::YOU SAID YOU DO HAVE KEY HUH?
:BUILDGRADLE
::SOME STUPID ENTER MANIC SESSION PREVENT YOU GET LOST
ECHO Opening Build.gradle...
PAUSE
CD /d E:/Leo/%PROJECT%/android/app
START build.gradle
ECHO I'm Going To Ask You Do Something By Your Own...
ECHO Ready?
PAUSE

ECHO "PLEASE COPY THE CODE BELOW IN YOUR FILE RIGHT UNDER DEFAULTCONFIG..."
@(
    ECHO signingConfigs {
    ECHO   release {
    ECHO     storeFile file(MYAPP_RELEASE_STORE_FILE)
    ECHO     storePassword MYAPP_RELEASE_STORE_PASSWORD
    ECHO     keyAlias MYAPP_RELEASE_KEY_ALIAS
    ECHO     keyPassword MYAPP_RELEASE_KEY_PASSWORD
    ECHO   }
    ECHO }
)
PAUSE
ECHO "AND HERE IS SOME OTHER, PLEASE PUT THEM AS THE LAST LINE OF BUILDTYPES > RELEASE"
ECHO signingConfig signingConfigs.release
PAUSE
::REMIND USER TO SAVE THE FILE
ECHO Did You Save The File Already?
PAUSE
ECHO Good!

:BUILDAPK
CD /d E:/Leo/%PROJECT%/android
START gradlew assembleRelease

::ASK IF USER WANT TO TRY IT ON LOCALHOST
ECHO Do You Want To Try It On Your Emulator Now?
SET /P EMULATE=(Y/N)?

::IF STATEMENT YOU KNOW
IF "%EMULATE%"=="Y" (
    GOTO EMULATOR
) ELSE IF "%EMULATE%"=="y" (
    GOTO EMULATOR
) ELSE IF "%EMULATE%"=="N" (
    GOTO OUTRO
) ELSE IF "%EMULATE%"=="n" (
    GOTO OUTRO
) ELSE (
    GOTO OUTRO
)
::SAY SOMETHING TO SHOW MY STUPIDITY
ECHO Alright!

:EMULATOR
::OPEN YOU OUTPUT FOLDER
%SystemRoot%\explorer.exe "e:\leo\%PROJECT%\android\app\build\outputs\apk"
::CHANGE DIRECTORY TO PROJECT OUTPUT FOLDER
CD /d E:/Leo/%PROJECT%/android/app/build/outputs/apk
::STARTING ADB AND INSTALL APK ON EMULATOR
START adb install app-release.apk
PAUSE

:OUTRO
::WELL DONE!
ECHO Here Is Your APK File!
ECHO Done!
PAUSE